#pragma once

#define BUFFER_SIZE 0x30000

#define FTS_PRAM_SADDR 0x000000
#define FTS_DRAM_SADDR 0xD00000
#define FTS_FLASH_PACKET_LENGTH_SPI (32 * 1024 - 16)

#define FTS_ROMBOOT_CMD_SET_PRAM_ADDR 0xAD
#define FTS_ROMBOOT_CMD_SET_PRAM_ADDR_LEN 4
#define FTS_ROMBOOT_CMD_WRITE 0xAE
#define FTS_ROMBOOT_CMD_START_APP 0x08

#define FTS_APP_INFO_OFFSET 0x100

NTSTATUS FTLoadFirmwareFile(WDFDEVICE Device, SPB_CONTEXT* SpbContext);